### ISSUE TITLE
1.0.7 has a bug with the Dice Roller

### ISSUE THREAD

**Issue by clevett** [3d-dice/dice-box#69] opened 2023-02-06 16:04 UTC
When trying to use Parser Interface + Dice Roller to do advanced parsing there is an error thrown when using. 

`const finalResults = DRP.parseFinalResults(results);`

The function below works fine in Dicebox 1.0.5 but breaks in 1.0.7

This is the function that I have in a [React hook](https://github.com/clevett/emeraldproductions/blob/master/client/src/components/DiceRoller/useDiceBox.tsx)

```
  if (dicebox) {
    // This method is triggered whenever dice are finished rolling
    dicebox.onRollComplete = (results: unknown) => {
      // handle any rerolls
      const rerolls = DRP.handleRerolls(results);
      if (rerolls.length) {
        rerolls.forEach((roll: { groupId: unknown }) =>
          dicebox.add(roll, roll.groupId)
        );
        return rerolls;
      }
      // if no rerolls needed then parse the final results
      const finalResults = DRP.parseFinalResults(results);
      setResult(finalResults);
    };
```

![Screenshot 2023-02-06 at 16 01 49](https://user-images.githubusercontent.com/10157460/217022150-e282ff62-da07-4b4a-bdee-1b9e251c47b6.png)

**Comment by frankieali** [comment] 2023-02-06 19:11
So, my best guess on this one is that this is related to the `flexible-dice-names` work I did. In this case, I removed the hardcoded dice id's that followed the pattern of `'d' + int`. This was done to allow for dice to be identified by their unique ids defined in the theme. Specifically, this was implemented for fate dice and rolls of `3df`.
To that end, the [advancedRoller](https://github.com/3d-dice/dice-ui/tree/main/src/advancedRoller) had some updates to accommodate this new output from dice-box. Take a look at this [commit](https://github.com/3d-dice/dice-ui/commit/9ce60db60620cb81996d8826881d0dda29ec2083) on dice-ui. The note in the code states `// convert string names back to intigers needed by DRP` (yup, I spelled integers wrong). 
Anyway, I think you need to update `dice-ui/` as well.

**Comment by frankieali** [comment] 2023-02-06 19:16
On sec ... perhaps I need to update the `dice-ui` npm package. It seems I committed the changes but did not publish an update.

**Comment by frankieali** [comment] 2023-02-06 20:11
Updated [Dice UI](https://www.npmjs.com/package/@3d-dice/dice-ui) to version `0.4.3`

**Comment by clevett** [comment] 2023-02-08 11:52
I'm not using Dice UI at all since I am writing my own UI for this.

`  "dependencies": {
    "@3d-dice/dice-box": "1.0.8",
    "@3d-dice/dice-parser-interface": "0.2.0"
  }`

which also installed the require dependency `"@3d-dice/dice-roller-parser": "^0.2.6"`

**Comment by frankieali** [comment] 2023-02-08 12:24
Ok, fair enough. The problem is still the same though. Dice-box is outputting the final result with `result.sides` as a string now. This needs to be converted back into an int before it gets to dice-roller-parser. This type check probably needs to be done in `dice-parser-interface` instead of `dice-ui`. I'll make an update.

**Comment by frankieali** [comment] 2023-02-08 14:38
Ok, I pushed an update to `@3d-dice/dice-parser-interface` and bumped the version to `0.2.1`. Give it a try.

**Comment by clevett** [comment] 2023-02-09 10:28
Thanks so much Frank! I'll try add the update today.

**Closed** 2023-07-03 13:50 UTC
